on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Praveen'
        required: true
        default: 'GitHub User'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.event.inputs.username }}!"
