name: Hello World

on:
  workflow_dispatch:  # allows manual runs from Actions tab

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions!"
